def renkmenu():
    print("\033[1;32;40m")
    print("\033[1;32;40m")
    #print("╔"+"═"*20+"╗")
    print("╔═════════════════════╗")
    print("║\033[1;31;40m  RENKLER          \033[1;32;40m  ║")
    print("║                     ║")
    print("║  1-Blue             ║")
    print("║  2-Red              ║")
    print("║  3-Purple           ║")
    print("║  4-Yellow           ║")
    print("║  5-Green            ║")
    print("║  6-Black            ║")
    print("║  7-White            ║")
    print("║  8-Orange           ║")
    print("║  9-                 ║")
    print("║  10-                ║")
    print("║                     ║")
    print("║    Seçimiz nedir?   ║")
    print("╚═════════════════════╝")

    secim = input("Seçiminiz nedir?")
