def oyunmenu():
    print("\033[1;32;40m")
    #print("╔"+"═"*20+"╗")
    print("╔═════════════════════╗")
    print("║\033[1;31;40m  OYUNLAR          \033[1;32;40m  ║")
    print("║                     ║")
    print("║  1-Tetris           ║")
    print("║  2-Adam Asmaca      ║")
    print("║  3-Voleybol         ║")
    print("║  4-Futbol           ║")
    print("║  5-Saklambaç        ║")
    print("║  6-Körebe           ║")
    print("║  7-Yakantop         ║")
    print("║  8-                 ║")
    print("║  9-                 ║")
    print("║  10-                ║")
    print("║                     ║")
    print("║    Seçimiz nedir?   ║")
    print("╚═════════════════════╝")